services:
  slap:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - slap-data:/app/tmp
      - ./conf:/app/conf:ro
    environment:
      - SLAP_JWT_SECRET=test
      - SLAP_CONF=conf/config-test.yaml

volumes:
  slap-data:
